spring:
  data:
    kafka:
      host: localhost
      port: 29092
      consumer:
        group-id: notification-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic:
        quotes:
          name: market.bybit.quotes
          partitions: 3

server:
  port: 8081

logging:
  level:
    root: info

services:
  user-service:
    host: localhost
    port: 8080