spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: strategy-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    properties:
      client.dns.lookup: use_all_dns_ips
    listener:
      ack-mode: manual

app:
  kafka:
    topic:
      market:
        name: market.bybit
        partitions: 3
      user:
        name: settings.rsi
        partitions: 3
      notification:
        name: notification.send
        partitions: 3
  timezone: Europe/Amsterdam
  rsi:
    strategy-counts:
      reset-cron: "0 0 0 * * *"

server:
  port: 8081

logging:
  level:
    root: info

services:
  user-service:
    base-url: http://localhost:8080

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  health:
    kafka:
      enabled: false